### ISSUE TITLE
Configurable HTTP proxy

### ISSUE THREAD

**Issue by mccarths** [twilio/authy-ruby#42]
Is it/would it be possible to configure this gem to make HTTP calls via a proxy? Possibly via an extra configuration item:
```
Authy.http_proxy = 'http://myproxy:8080'
```
Then included in the call to `IncludeClient` in `api.rb` or something similar:
```
include_http_client(Authy.http_proxy, ...
```

**Comment by igormoraisazevedo** [comment]
This functionality is very important, especially for computers with Internet access via static or authenticated Proxy.

**Comment by philnash** [comment]
This project uses [httpclient](https://github.com/nahi/httpclient) to make requests. You can provide a proxy to httpclient by setting the `HTTP_PROXY` environment variable.

I will also note that we currently recommend the use of [Twilio Verify](https://www.twilio.com/docs/verify). The Verify API is an evolution of the Authy API and is where new features are built. The Verify API can be used with the [twilio-ruby](https://github.com/twilio/twilio-ruby/) gem which also supports providing a proxy via a [custom HTTP client](https://www.twilio.com/docs/libraries/ruby/custom-http-clients).

I'm going to close this issue, but please let me know if you have any other questions.
