### ISSUE TITLE
unknown attribute 'authy_id' for Host/member/owner .

### ISSUE THREAD

**Issue by mr3abd** [twilio/authy-ruby#45]
Hello, 
when trying to use devise and write that in a controller to verify User with SMS 

```
`  def create

    super do |host|
   authy = Authy::API.register_user(
     email: host.email,
     cellphone: host.phone_number,
     country_code: host.country_code
   )
   host.update(authy_id: authy.id)
 end
  end`
```

and I show when trying to make an account 
unknown attribute 'authy_id' for Host .

**Comment by philnash** [comment]
If you are using Authy with Devise then I can recommend you take a look at [Authy-Devise](https://github.com/twilio/authy-devise/) as it handles a lot of this stuff for you.

Otherwise, it looks to me as though you are trying to update an attribute on your `Host` model that doesn't exist. You need to create a migration to add a string field called `authy_id` to your hosts table so that you can save the `authy_id` from the API response in it.

Let me know how you get on with that.

**Comment by mr3abd** [comment]
I want when to make registration send the activation code to the confirmation user account 

Can Authy-Devise make that, + rest password with SMS ?

**Comment by philnash** [comment]
This all depends. What are you try to build? The API you were using in the first post lets you implement two factor authentication in your application.

Authy doesn't handle password resets for your application. You could build that with the regular [Twilio Messaging API](https://www.twilio.com/docs/sms/send-messages?code-sample=code-send-an-sms-message&code-language=Ruby&code-sdk-version=5.x) though.

What are you trying to achieve here?

**Comment by mr3abd** [comment]
I want to build a verification for account and user can make a request to reset a password with SMS replace email

**Comment by mr3abd** [comment]
and when create the migration authy_id 

authy_id be nil

**Comment by mr3abd** [comment]
Really thanks for your helping :1st_place_medal:  ^^ 

my last question how to make a redirect in devise controller in sing up ? 

I try to use

`redirect_to  phone_verifications_path`
and 
`    sign_in_and_redirect phone_verifications_path and return`
not working 

can help me ?

**Comment by philnash** [comment]
To redirect after sign up you should implement your own `RegistrationsController` and override the `after_sign_up_path_for` method to return the path you want to redirect to. Like

```ruby
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    phone_verifications_path
  end
end
```
