### ISSUE TITLE
Time request it's to big ! 

### ISSUE THREAD

**Issue by mr3abd** [twilio/authy-ruby#49]
Hello , 

When make put 

 ```
     response = Authy::PhoneVerification.start(
       via: params[:sms],
       country_code: @host.country_code,
       phone_number: @host.phone_number
     )

```
in sing_up have a big number in time request 
like "1863 ms" that in postman

that will solve when upgrading in the premium plan in twillo ?

**Comment by mr3abd** [comment]
I try to make SMS request in rails g job but can't provide user a number phone

**Comment by mr3abd** [comment]
done solved

**Comment by philnash** [comment]
Glad you got this sorted. And good plan going with a background job. API requests rely on the network as well as the work that the Twilio API has to do when it receives the request. It's best to do them outside of a controller.

If it helps, I wrote up [how to send a text message using ActiveJob](https://www.twilio.com/blog/2015/10/delay-api-calls-to-twilio-with-rails-active-job-and-sidekiq.html) which has a lot of similarities to what you're doing.
