### ISSUE TITLE
Any way to be able to see the exact content of sms sent to a user (inside a test)?

### ISSUE THREAD

**Issue by yanshney** [twilio/authy-ruby#54]
Hello,

Thank you for you work! 
I have an app that sends an sms with a verification code to users during signup.

I send it like this: Authy::API.request_sms(:id => user.authy_id)

I was wondering if it is possible to see the exact content of this sms (along with the verification code) during my testing, so I could just directly put the code into the input field when I run my capybara signup test.

Thank you,
Yan

**Comment by philnash** [comment]
Hey @yanshney! Unfortunately the API does not expose the code or the text of the message sent to the user.

However, I wouldn't recommend testing third party services, even as part of your end to end testing. Given the reliance on a network in order to call the API, that you'd be testing a third party library (this one) and the fact that this would trigger an SMS in real life, it doesn't lend itself to good tests.

Instead I would mock the API response for both the sending and verifying part of the test.

What do you think?

**Comment by yanshney** [comment]
Hi Phil!

Thanks so much for your response!

I know I can use the VCR gem in order to mock the API response, and there
is an example online for that, but how would I mock the verification part
if I don't know the verification token I need to input?

Thank you,
Yan

**Comment by philnash** [comment]
VCR can be used to mock an API response, but you could mock closer to your system than that. For example, you can mock the [`Authy::API.verify` method](https://github.com/twilio/authy-ruby#verifying-a-user) to expect to receive an authy ID and a token and return an object that returns `true` in response to the `ok?` method.

You can also test the unhappy path, where you deal with a user entering an incorrect token. You'd still expect the same the same parameters, but the response object would respond `false` to the `ok?` method.

Alternatively, if you do want to use VCR, you could record the result of a real use of the API, where you receive the SMS and use the correct code outside of your tests, and set that result up as the VCR tape.

**Comment by philnash** [comment]
Glad to hear that the happy path is working for you.

To test the unhappy path, either a wrong code or an API failure, you can continue mocking the response but with different values. You can, for example, create a cassette with a non-200 response or a response where the token was invalid (you can create this one in the same way you generated the happy path, by interrupting but entering the wrong code). You can see what [error response will look like in the documentation here](https://www.twilio.com/docs/authy/return-and-error-codes).

**Comment by yanshney** [comment]
I see, thanks a lot for all the help Phil!
