### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by robinske** [twilio/authy-ruby#56]
Flaky test failure occurred on README only changes:
https://travis-ci.org/twilio/authy-ruby/jobs/584230201
https://travis-ci.org/twilio/authy-ruby/jobs/595194891

https://github.com/twilio/authy-ruby/blob/2ebee7c71b2f2317a436a27c77a1217e0a192def/spec/authy/api_spec.rb#L230

```
  1) Authy::API user status user exists should be ok
     Failure/Error: super(name, *args, &block)
     
     NoMethodError:
       undefined method `status' for #<Authy::Response:0x00000003a75fc8>
     # ./lib/authy/response.rb:47:in `method_missing'
     # ./spec/authy/api_spec.rb:232:in `block (4 levels) in <top (required)>'
```

**Comment by philnash** [comment]
Tests now don't use the sandbox or network, so are no longer flaky. Closing!
