### ISSUE TITLE
missing two api calls

### ISSUE THREAD

**Issue by robinw777** [twilio/authy-ruby#67]
request email: https://www.twilio.com/docs/authy/email?code-sample=code-send-a-one-time-passcode-via-email-1&code-language=curl&code-sdk-version=default
and update user's email: https://www.twilio.com/docs/authy/email?code-sample=code-update-authy-user-email-1&code-language=curl&code-sdk-version=default

**Comment by philnash** [comment]
Thanks for this, I finally got around to adding this in. Check out the new version 3.0.0 of the gem.
